### ISSUE TITLE
A question about your paper

### ISSUE THREAD

**Issue by pyni** [tjiiv-cprg/EPro-PnP#5]
Hi~
Thanks for your wonderful work. 
I have a question about your paper. Why you choose a mixture of von Mises and uniform distribution rather than t-distribution or just uniform distribution to be the proposal distribution of 1D orientation?
Could you please give me some suggestions about how to choose the proposal distribution? 

Thanks~

Another question is about the Jacobian J. Since your final optimization target is changed from equation 1 to equation 5, why J still equals to ∂fi(y)/∂y? (The Lpred in equation 5 is not considered in this Jacobian J I think.)

**Comment by Lakonik** [comment]
Hi! Thank you for your interest on our work.

We chose the mixture distribution for 1D orientation partly for convenience, as von Mises is already implemented in PyTorch/NumPy. Plain uniform distribution is not meant for importance sampling. The general rules of thumb are:
- Use heavy-tailed distributions (e.g., use t-distribution instead of normal distribution)
- Use distributions with fast implementations of `rsample` and `log_prob` functions, and parameter estimation should be easy as well.
Another suggestion is you may consider mixture distributions for ambiguous 3D orientation, as it's not covered in the paper. 

There are actually two optimization problems in the paper. Eq. 1 defines the PnP optimization as a declarative layer within the model, while Eq. 5 defines the training objective for optimizing the network.  The Jacobian is in the context of the PnP solver.

**Comment by pyni** [comment]
Wow! That's awesome.
I am clear now. Thanks for your replying.
